# Generated by Django 2.0.5 on 2018-07-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20180720_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privkey',
            field=models.CharField(default=None, max_length=2048),
        ),
        migrations.AddField(
            model_name='user',
            name='pubkey',
            field=models.CharField(default=None, max_length=2048),
        ),
    ]
