# Generated by Django 2.0.5 on 2018-07-23 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20180723_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.FileField(upload_to='upload/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='privkey',
            field=models.CharField(default=' ', max_length=2048),
        ),
        migrations.AlterField(
            model_name='user',
            name='pubkey',
            field=models.CharField(default=' ', max_length=2048),
        ),
    ]
