# Generated by Django 2.0.5 on 2018-07-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20180723_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='enckey',
            field=models.BinaryField(default=' ', max_length=2048),
        ),
        migrations.AlterField(
            model_name='file',
            name='sha256',
            field=models.BinaryField(default=' ', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='privkey',
            field=models.BinaryField(default=' ', max_length=2048),
        ),
        migrations.AlterField(
            model_name='user',
            name='pubkey',
            field=models.BinaryField(default=' ', max_length=2048),
        ),
    ]
