# Generated by Django 2.0.5 on 2018-07-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20180724_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='enckey',
            field=models.CharField(default=' ', max_length=2048),
        ),
        migrations.AlterField(
            model_name='file',
            name='sha256',
            field=models.CharField(default=' ', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='privkey',
            field=models.CharField(default=' ', max_length=2048),
        ),
        migrations.AlterField(
            model_name='user',
            name='pubkey',
            field=models.CharField(default=' ', max_length=2048),
        ),
    ]
