# Generated by Django 2.0.5 on 2018-08-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20180724_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default=' ', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='privkey',
            field=models.CharField(default=' ', max_length=4096),
        ),
        migrations.AlterField(
            model_name='user',
            name='pubkey',
            field=models.CharField(default=' ', max_length=4096),
        ),
    ]
